services:
  payment-odl-front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: payment-odl-front:latest
    ports:
      - "3000:3000"
    restart: always
    container_name: payment-odl-front

  payment-odl-back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: payment-odl-back:latest
    ports:
      - "3030:3030"
    restart: always
    container_name: payment-odl-back